import { motion } from "framer-motion";
import { Link } from "wouter";
import { ArrowLeft, FileText } from "lucide-react";
import { useBackground } from "@/hooks/use-background";
import { BACKGROUND_THEMES } from "@/lib/themes";

export default function Terms() {
  const { bgIndex } = useBackground();
  const theme = BACKGROUND_THEMES[bgIndex];
  const lastUpdated = "April 26, 2026";

  return (
    <div className="min-h-screen bg-transparent flex flex-col">
      <header className="border-b border-border/40 bg-white/60 backdrop-blur-sm px-6 py-4">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors font-medium"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Recipe Finder
        </Link>
      </header>

      <div
        className="py-8 sm:py-12 md:py-16 px-4 text-center relative overflow-hidden transition-all duration-700"
        style={theme.heroStyle}
      >
        <motion.div
          initial={{ opacity: 0, y: -16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="relative z-10"
        >
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/60 backdrop-blur-sm text-primary font-medium text-sm border border-primary/20 shadow-sm mb-6">
            <FileText className="w-4 h-4" />
            The fine print
          </span>
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-display text-foreground leading-tight">
            Terms of Service
          </h1>
        </motion.div>
      </div>

      <main className="flex-1 container max-w-3xl mx-auto px-3 sm:px-4 py-8 sm:py-10 md:py-14">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="bg-white/90 backdrop-blur-sm rounded-2xl sm:rounded-3xl shadow-sm border border-border/50 overflow-hidden"
        >
          <div className="h-2 bg-gradient-to-r from-orange-400 via-amber-400 to-orange-300" />
          <div className="p-6 sm:p-8 md:p-10 space-y-6 text-sm sm:text-base text-foreground/80 leading-relaxed">
            <p className="text-xs text-muted-foreground">Last updated: {lastUpdated}</p>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using AI Recipe Finder, you agree to be bound by these Terms of Service. If
                you do not agree, please do not use the service.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">2. Service Description</h2>
              <p>
                AI Recipe Finder is a free web tool that generates recipe suggestions using artificial
                intelligence based on a dish name and any dietary preferences or allergies you provide.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">3. AI-Generated Content Disclaimer</h2>
              <p className="mb-2">
                Recipes are generated by an AI model and may contain errors, inaccuracies, or omissions.
                <strong> Always use your own judgment when cooking.</strong> In particular:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Verify ingredient safety yourself if you have allergies or medical conditions.</li>
                <li>Cook all foods to safe internal temperatures.</li>
                <li>Consult a qualified professional for medical, dietary, or nutritional advice.</li>
              </ul>
              <p className="mt-2">
                We make no guarantees about the accuracy, completeness, or suitability of any recipe.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">4. Acceptable Use</h2>
              <p className="mb-2">You agree not to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Use the service for any unlawful purpose.</li>
                <li>Attempt to disrupt, overload, or reverse-engineer the service.</li>
                <li>Submit content that is harmful, abusive, or infringes on others' rights.</li>
                <li>Scrape or republish AI-generated content at scale without permission.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">5. Intellectual Property</h2>
              <p>
                The AI Recipe Finder name, design, and original code are owned by us. You are free to cook,
                share, and use the recipes generated for personal, non-commercial purposes.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">6. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, AI Recipe Finder, its operators, and contributors are
                not liable for any direct, indirect, incidental, or consequential damages arising from your
                use of the service or any AI-generated content, including but not limited to allergic
                reactions, food poisoning, or property damage.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">7. Service Availability</h2>
              <p>
                The service is provided "as is" without any warranties. We may modify, suspend, or
                discontinue any part of the service at any time without notice.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">8. Changes to These Terms</h2>
              <p>
                We may revise these Terms from time to time. The "Last updated" date at the top of this page
                will reflect the most recent revision. Continued use of the service after changes constitutes
                acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl sm:text-2xl font-display text-foreground mb-3">9. Contact</h2>
              <p>
                Questions about these Terms? Email us at{" "}
                <a
                  href="mailto:ayaan.kriplani2212@gmail.com"
                  className="text-primary underline hover:text-primary/80"
                >
                  ayaan.kriplani2212@gmail.com
                </a>
                .
              </p>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
